from pr_reviewer.review.models import Finding, Severity
from pr_reviewer.review.quality_gate import (
    QualityGateDecision,
    QualityGateResult,
)


class ReviewSummaryFormatter:
    SEVERITY_LABELS = {
        Severity.CRITICAL: "🔴 Critical",
        Severity.HIGH: "🟠 High",
        Severity.MEDIUM: "🟡 Medium",
        Severity.LOW: "🔵 Low",
        Severity.SUGGESTION: "🟢 Suggestion",
    }

    DECISION_LABELS = {
        QualityGateDecision.BLOCK: "❌ Block Merge",
        QualityGateDecision.REQUEST_CHANGES: "🛑 Request Changes",
        QualityGateDecision.REVIEW_RECOMMENDED: "⚠️ Review Recommended",
        QualityGateDecision.NON_BLOCKING: "ℹ️ Non-blocking Issues",
        QualityGateDecision.OPTIONAL: "✅ Optional Improvements",
        QualityGateDecision.PASS: "✅ Passed",
    }

    def format(
        self,
        findings: list[Finding],
        quality_gate: QualityGateResult,
    ) -> str:
        lines: list[str] = []

        lines.append("## 🤖 Intelligent PR Review")
        lines.append("")

        decision_label = self.DECISION_LABELS[
            quality_gate.decision
        ]

        lines.append(
            f"**Decision:** {decision_label}"
        )
        lines.append("")

        lines.append("### Review Summary")
        lines.append("")

        lines.append(
            f"- 🔴 Critical: {quality_gate.critical_count}"
        )
        lines.append(
            f"- 🟠 High: {quality_gate.high_count}"
        )
        lines.append(
            f"- 🟡 Medium: {quality_gate.medium_count}"
        )
        lines.append(
            f"- 🔵 Low: {quality_gate.low_count}"
        )
        lines.append(
            f"- 🟢 Suggestion: {quality_gate.suggestion_count}"
        )

        lines.append("")
        lines.append(
            f"**Total findings:** {quality_gate.total_findings}"
        )

        if not findings:
            lines.append("")
            lines.append(
                "✅ No meaningful issues were detected in the changed code."
            )

            return "\n".join(lines)

        grouped_findings = self._group_by_severity(
            findings
        )

        lines.append("")
        lines.append("### Findings")

        for severity in [
            Severity.CRITICAL,
            Severity.HIGH,
            Severity.MEDIUM,
            Severity.LOW,
            Severity.SUGGESTION,
        ]:
            severity_findings = grouped_findings.get(
                severity,
                [],
            )

            if not severity_findings:
                continue

            lines.append("")
            lines.append(
                f"#### {self.SEVERITY_LABELS[severity]}"
            )
            lines.append("")

            for finding in severity_findings:
                lines.append(
                    f"- `{finding.file_path}:{finding.line_number}` "
                    f"**{finding.rule_id}** — {finding.message}"
                )

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "_Generated by Intelligent PR Reviewer_"
        )

        return "\n".join(lines)

    @staticmethod
    def _group_by_severity(
        findings: list[Finding],
    ) -> dict[Severity, list[Finding]]:
        grouped: dict[
            Severity,
            list[Finding],
        ] = {}

        for finding in findings:
            grouped.setdefault(
                finding.severity,
                [],
            ).append(finding)

        return grouped