import {
  ChangedFileSummary,
  PullRequestDetail,
  PullRequestSummary,
  ReviewFinding,
  ReviewJob,
  ReviewResult,
} from './models';

export const DEMO_PULL_REQUESTS: PullRequestSummary[] = [
  {
    number: 48,
    title: 'Improve checkout validation',
    author: 'Maya Patel',
    base_branch: 'main',
    head_branch: 'feature/checkout-validation',
    state: 'active',
    changed_files: 18,
    updated_at: '8 min ago',
    review_status: 'awaiting',
  },
  {
    number: 47,
    title: 'Harden payment webhook verification',
    author: 'Daniel Kim',
    base_branch: 'main',
    head_branch: 'security/webhook-signature',
    state: 'active',
    changed_files: 7,
    updated_at: '24 min ago',
    review_status: 'blocked',
  },
  {
    number: 46,
    title: 'Add product search result caching',
    author: 'Amelia Stone',
    base_branch: 'main',
    head_branch: 'feature/search-cache',
    state: 'active',
    changed_files: 11,
    updated_at: '1 hr ago',
    review_status: 'passed',
  },
  {
    number: 45,
    title: 'Refactor order repository pagination',
    author: 'Noah Williams',
    base_branch: 'develop',
    head_branch: 'refactor/order-pagination',
    state: 'active',
    changed_files: 9,
    updated_at: '2 hrs ago',
    review_status: 'awaiting',
  },
  {
    number: 44,
    title: 'Update CI deployment protections',
    author: 'Olivia Martin',
    base_branch: 'main',
    head_branch: 'ci/protected-deployments',
    state: 'active',
    changed_files: 4,
    updated_at: 'Yesterday',
    review_status: 'passed',
  },
];

export const DEMO_PULL_REQUEST: PullRequestDetail = {
  ...DEMO_PULL_REQUESTS[0],
  provider: 'azure-devops',
  repository: 'noventra-ai-labs/pr-reviewer-lab/pr-reviewer-lab',
  head_commit: '9d2a17f6b2c4',
  description:
    'Strengthens checkout validation, isolates payment parsing, and adds regression coverage for invalid cart state before order submission.',
};

export const DEMO_FILES: ChangedFileSummary[] = [
  {
    file_path: 'apps/shop/src/app/checkout/checkout.service.ts',
    status: 'modified',
    language: 'typescript',
    changed_line_count: 52,
    additions: 41,
    deletions: 11,
  },
  {
    file_path: 'apps/shop/src/app/checkout/checkout.component.html',
    status: 'modified',
    language: 'html',
    changed_line_count: 18,
    additions: 14,
    deletions: 4,
  },
  {
    file_path: 'libs/data/src/lib/order.repository.ts',
    status: 'modified',
    language: 'typescript',
    changed_line_count: 35,
    additions: 29,
    deletions: 6,
  },
  {
    file_path: 'apps/api/src/orders/order.controller.ts',
    status: 'modified',
    language: 'typescript',
    changed_line_count: 27,
    additions: 21,
    deletions: 6,
  },
  {
    file_path: 'apps/shop/src/app/checkout/checkout.service.spec.ts',
    status: 'added',
    language: 'typescript',
    changed_line_count: 68,
    additions: 68,
    deletions: 0,
  },
];

export const DEMO_FINDINGS: ReviewFinding[] = [
  {
    file_path: 'apps/api/src/orders/order.controller.ts',
    line_number: 88,
    severity: 'critical',
    rule_id: 'authorization',
    message: 'Caller-controlled request data is trusted as authorization evidence.',
    issue: 'The checkout endpoint trusts a client-provided role before creating the order.',
    impact: 'A caller can bypass the intended authorization boundary and create privileged orders.',
    evidence: "Changed line 88: if (request.headers['x-user-role'] === 'admin')",
    suggestion: 'Resolve the authenticated principal on the server and enforce the order policy from trusted claims.',
    source: 'static',
    category: 'Security',
    confidence: 'high',
  },
  {
    file_path: 'apps/shop/src/app/checkout/checkout.service.ts',
    line_number: 42,
    severity: 'high',
    rule_id: 'empty-catch-block',
    message: 'The parsing failure is silently ignored.',
    issue: 'The parsing failure is silently ignored.',
    impact: 'Invalid response data may be treated as valid state and cause incorrect downstream behavior.',
    evidence: 'Changed line 42: } catch (error) {}',
    suggestion: 'Handle the parsing failure explicitly, propagate the error, or return a defined fallback result.',
    source: 'static',
    category: 'Reliability',
    confidence: 'high',
  },
  {
    file_path: 'libs/data/src/lib/order.repository.ts',
    line_number: 71,
    severity: 'medium',
    rule_id: 'fetch-status-not-checked',
    message: 'The HTTP response is consumed without validating its status.',
    issue: 'The repository parses every response as a successful order payload.',
    impact: 'Error responses can flow into application state as if they were valid orders.',
    evidence: 'Changed lines 70–71 call fetch() and response.json() without checking response.ok.',
    suggestion: 'Check response.ok and map non-success responses to a defined domain error.',
    source: 'static',
    category: 'Reliability',
    confidence: 'high',
  },
  {
    file_path: 'apps/shop/src/app/checkout/checkout.service.spec.ts',
    line_number: 59,
    severity: 'low',
    rule_id: 'insufficient-test-assertion',
    message: 'The test checks truthiness rather than the expected checkout state.',
    issue: 'The regression test can pass for an incorrect non-empty result.',
    impact: 'A behavior regression may reach production while the test suite remains green.',
    evidence: 'Changed line 59: expect(result).toBeTruthy()',
    suggestion: 'Assert the exact status, order identifier, and emitted validation error.',
    source: 'framework',
    category: 'Test quality',
    confidence: 'high',
  },
];

export const DEMO_RESULT: ReviewResult = {
  pull_request: DEMO_PULL_REQUEST,
  findings: DEMO_FINDINGS,
  quality_gate: {
    decision: 'block',
    critical_count: 2,
    high_count: 11,
    medium_count: 30,
    low_count: 13,
    suggestion_count: 0,
    total_findings: 56,
  },
  publishing: {
    published_comments: [],
    skipped_duplicates: 0,
    failed_comments: [],
    summary_only_findings: 16,
    grouped_findings: 3,
    rate_limited: false,
  },
  summary_publishing: null,
  dry_run: true,
  diagnostics: {
    changed_files: 18,
    ai_review_files: 5,
    review_batches: 2,
    skipped_files: 13,
    context_only_files: 6,
    semantic_skipped_files: 3,
    review_depth: 'standard',
    skipped_by_category: { documentation: 2, tooling: 4 },
    skipped_by_reason: { 'context-only metadata': 6 },
    review_files_by_project: { shop: 3, api: 2 },
    planned_llm_calls: 2,
    actual_llm_calls: 2,
    llm_retries: 0,
    failed_llm_parts: 0,
    llm_prompt_tokens: 6842,
    llm_generated_tokens: 526,
    raw_ai_findings: 4,
    final_ai_findings: 1,
    static_analysis_seconds: 0.82,
    llm_review_seconds: 21.34,
    total_review_seconds: 24.18,
  },
  summary_publishing_failure: null,
};

export const DEMO_JOB: ReviewJob = {
  id: 'RVW-7F3A91',
  command: {
    provider: 'azure-devops',
    repository: DEMO_PULL_REQUEST.repository,
    pull_number: DEMO_PULL_REQUEST.number,
    review_depth: 'standard',
    publish: false,
  },
  status: 'running',
  phase: 'ai_review',
  progress: 64,
  message: 'Reviewing 5 application files across 2 compatible batches',
  created_at: new Date(Date.now() - 90_000).toISOString(),
  started_at: new Date(Date.now() - 88_000).toISOString(),
  completed_at: null,
  error: null,
  steps: [
    { key: 'queued', label: 'Queued', state: 'complete', message: null, updated_at: null },
    { key: 'discovery', label: 'Discovery', state: 'complete', message: null, updated_at: null },
    {
      key: 'static_analysis',
      label: 'Static analysis',
      state: 'complete',
      message: '55 deterministic findings',
      updated_at: null,
    },
    {
      key: 'ai_review',
      label: 'AI review',
      state: 'active',
      message: 'Batch 2 of 2',
      updated_at: null,
    },
    { key: 'validation', label: 'Validation', state: 'pending', message: null, updated_at: null },
    { key: 'publishing', label: 'Publishing', state: 'pending', message: null, updated_at: null },
    { key: 'completed', label: 'Completed', state: 'pending', message: null, updated_at: null },
  ],
};
