import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideRouter } from '@angular/router';

import {
  LucideActivity,
  LucideArrowLeft,
  LucideArrowRight,
  LucideBadgeCheck,
  LucideBot,
  LucideBraces,
  LucideBuilding2,
  LucideCalendar,
  LucideCheck,
  LucideCheckCircle2,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleDot,
  LucideCirclePlay,
  LucideClock3,
  LucideCloud,
  LucideCode2,
  LucideCopy,
  LucideDatabase,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideFileCode2,
  LucideFileDiff,
  LucideFileText,
  LucideFilter,
  LucideGitBranch,
  LucideGitPullRequest,
  LucideHistory,
  LucideLayoutDashboard,
  LucideListFilter,
  LucideLoaderCircle,
  LucideLockKeyhole,
  LucideMenu,
  LucideMessageSquareText,
  LucideMoon,
  LucideMoreHorizontal,
  LucideOctagonAlert,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePlay,
  LucideRefreshCw,
  LucideRocket,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShieldCheck,
  LucideSlidersHorizontal,
  LucideSparkles,
  LucideSun,
  LucideTerminalSquare,
  LucideTestTube2,
  LucideTimer,
  LucideTriangleAlert,
  LucideUserRound,
  LucideWorkflow,
  LucideX,
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideHttpClient(withFetch()),
    provideRouter(routes),
    provideLucideConfig({ size: 18, strokeWidth: 1.8 }),
    provideLucideIcons(
      LucideActivity,
      LucideArrowLeft,
      LucideArrowRight,
      LucideBadgeCheck,
      LucideBot,
      LucideBraces,
      LucideBuilding2,
      LucideCalendar,
      LucideCheck,
      LucideCheckCircle2,
      LucideChevronDown,
      LucideChevronLeft,
      LucideChevronRight,
      LucideCircleAlert,
      LucideCircleCheck,
      LucideCircleDot,
      LucideCirclePlay,
      LucideClock3,
      LucideCloud,
      LucideCode2,
      LucideCopy,
      LucideDatabase,
      LucideDownload,
      LucideExternalLink,
      LucideEye,
      LucideFileCode2,
      LucideFileDiff,
      LucideFileText,
      LucideFilter,
      LucideGitBranch,
      LucideGitPullRequest,
      LucideHistory,
      LucideLayoutDashboard,
      LucideListFilter,
      LucideLoaderCircle,
      LucideLockKeyhole,
      LucideMenu,
      LucideMessageSquareText,
      LucideMoon,
      LucideMoreHorizontal,
      LucideOctagonAlert,
      LucidePanelLeftClose,
      LucidePanelLeftOpen,
      LucidePlay,
      LucideRefreshCw,
      LucideRocket,
      LucideSearch,
      LucideServer,
      LucideSettings,
      LucideShieldCheck,
      LucideSlidersHorizontal,
      LucideSparkles,
      LucideSun,
      LucideTerminalSquare,
      LucideTestTube2,
      LucideTimer,
      LucideTriangleAlert,
      LucideUserRound,
      LucideWorkflow,
      LucideX,
    ),
  ],
};
